### ISSUE TITLE
Error when running on IIS with IIS Node

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#93] opened 2016-10-03 08:20 UTC
```
Error: Not Found
    at C:\adminkb\app.js:215:15
    at Layer.handle [as handle_request] (C:\adminkb\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\adminkb\node_modules\express\lib\router\index.js:270:13)
    at C:\adminkb\node_modules\express\lib\router\index.js:237:9
    at Function.proto.process_params (C:\adminkb\node_modules\express\lib\router\index.js:312:12)
    at C:\adminkb\node_modules\express\lib\router\index.js:228:12
    at Function.match_layer (C:\adminkb\node_modules\express\lib\router\index.js:295:3)
    at next (C:\adminkb\node_modules\express\lib\router\index.js:189:10)
    at C:\adminkb\node_modules\express\lib\router\index.js:560:15
    at next (C:\adminkb\node_modules\express\lib\router\index.js:186:14)
```

**Comment by mrvautin** [comment] 2016-10-03 08:23
That is a 404 not found. 

Is the data files being created on startup or are you using Mongodb? I've used IIS node before and had massive issues with file permissions.

**Comment by thedaftbadger** [comment] 2016-10-03 09:28
Seem to have the file permissions sorted.
It is when pasting an image into the editor.

**Comment by mrvautin** [comment] 2016-10-03 09:38
That would be the Async file upload. I think it's definitely a permissions problem on the `inline_files` directory.

**Comment by thedaftbadger** [comment] 2016-10-04 11:15
Checked the permissions on the `inline_files` directory and set it to Everyone Allow All.
Existing uploads are fine and work, just adding new ones where the bug seems to be.

The actually upload properly to the `inline_files` directory but aren't showing in the article or editor.

![image](https://cloud.githubusercontent.com/assets/13657363/19072222/f75e170e-8a2b-11e6-8598-51774e40f1a3.png)

![image](https://cloud.githubusercontent.com/assets/13657363/19072242/12c47952-8a2c-11e6-8031-76e408cdfb96.png)

![image](https://cloud.githubusercontent.com/assets/13657363/19072278/450c1fe6-8a2c-11e6-9e38-13da6bec55af.png)

**Comment by mrvautin** [comment] 2016-10-26 23:57
Did you figure this out or still an issue @thedaftbadger?

**Comment by Mucaccino** [comment] 2016-10-28 18:17
Hello, I have the same problem here.

It certainly is not a permissions issue, because the images are allocated in the folder and with the correct adress on browser the image was showed.

Noting seems that the link is incorrectly formatted with something similar to an html encode, breaking the link to the image.

![screenshot_5](https://cloud.githubusercontent.com/assets/399292/19817371/112fc482-9d2a-11e6-99d8-56b039fc5f6c.png)

+1 To solve this issue.

**Comment by mrvautin** [comment] 2016-10-28 21:34
I don't have a windows environment which I can use to replicate nor am I an expert with IIS. 

Is seems the issue is the slashes encoding with `%5C` which is a `\` but should be `%2F` or a `/`.

There must be an issue resolving the path somewhere. I will have a look further when I get time.

**Comment by mrvautin** [comment] 2016-10-28 22:54
What does the source Markdown show in the editor? Is it correct there? @thedaftbadger @Mucaccino

**Comment by mrvautin** [comment] 2016-10-28 23:36
Let me know if the last commit fixed the issue. cc @thedaftbadger @Mucaccino

**Comment by Mucaccino** [comment] 2016-10-31 15:45
Hi, @mrvautin!
Thanks to review and assert this issue.
Now is able to make correct links when upload new files directly.
However i needed to change the '\' to '/' of previous self-created links.
Anyway, this is solved! Grateful.

**Comment by mrvautin** [comment] 2016-10-31 23:32
👍

**Closed by mrvautin** 2016-10-31 23:32 UTC

**Comment by thedaftbadger** [comment] 2016-11-01 16:23
Been busy with other projects. I'll spin up a test in IIS node and test today / tomorrow 👍
