### ISSUE TITLE
Search Freezing

### ISSUE THREAD

**Issue by william00179** [mrvautin/openKB#171] opened 2017-04-25 22:20 UTC
If you type one single character in the search field with a small delay until the next one it causes the whole tab to freeze.

Typing an entire word quickly does not have this problem and the page stays responsive.

I am not even able to investigate the issue and supply you with some leads as it totally freezes my tab so I unable to use any debug tools. This also happens across multiple browsers. I have tested the bug on Google Chrome, Safari, Firefox.

I am using the standard install of openKB, with the mongoDB backend.

**Comment by william00179** [comment] 2017-04-25 23:13
Upon further investigation, the script is freezing at
`var results = index.search(query);` in openkb.js.

I have enabled the index article body setting. Upon disabling this setting the search function operates as one would expect. There are only currently two articles in my KB so I wouldn't expect the load would be too high with full-text search on the Lunr framework.

It would seem this query is taking too long and causing the framework to freeze.

**Comment by davidhr** [comment] 2017-05-11 12:48
When moving our KB to openKB today, I found this very annoying issue. 
@william00179 have you found a solution ? Thanks.

**Comment by mrvautin** [comment] 2017-05-11 13:23
Sorry I've totally missed this issue.

I cannot replicate the issue. Does the issue occur [here](https://openkb.markmoffat.com)?

**Comment by davidhr** [comment] 2017-05-11 13:42
@mrvautin no your openkb website just work fine! 
I don't know if it is related: my OS is Centos 7 + Apache2 + proxy + mongodb. The issue also appeared without using proxy. 

As the Ajax call is made with jquery (in openkb.js), I just updated the module to jquery 3.2.1 and the issue seems to have disappeared for the moment. I'll confirm later after many more searches on new KBs.

**Comment by davidhr** [comment] 2017-05-11 14:06
Unfortunately, the issue reappeared after inserting a new KB.

**Comment by mrvautin** [comment] 2017-05-11 21:52
Are there any errors in the browser console? Is this a public FAQ? Something I can look at?

**Comment by davidhr** [comment] 2017-05-12 10:01
I had no warnings/errors in the console, just a complete freeze of the browser (or of the tab). I've installed openkb on our intranet, so not accessible from the Internet. I think Nedb should be sufficient for our IT faqs. 

I think the problem is somewhere in the communication between  Lunr and Mongodb. I'm using Mongodb 3.2.13. Openkb use Lunr 0.7.2; maybe an update to the latest version (2.0.3) will fix the problem, don't know, I'll investigate if I have time. 

Thanks for this project and your help.

**Comment by mrvautin** [comment] 2017-05-12 10:57
I'm not sure upgrading those libraries will help. I'm running it on Centos with Nginx front end. 

I will have to look into it further. Really hard when I can't reproduce it locally though. Thanks for your input thus far.

**Comment by mrvautin** [comment] 2017-05-12 10:58
Just re-read your comment above. 

Can you confirm this issue only occurs when running with MongoDB and not NeDB?

**Comment by davidhr** [comment] 2017-05-12 11:45
Yes I confirm, no problem with nedb, only with mangodb.

**Comment by mrvautin** [comment] 2017-05-15 12:38
I've tested and still cannot replicate with Mongodb backend. 

Can you confirm approximately how many articles you have?

**Comment by william00179** [comment] 2017-05-15 20:17
I have five at the moment and the issue occurs. There are no error logs to the browser console. The script reaches the `var results = index.search(query);` and just simply hangs there.

**Comment by mrvautin** [comment] 2017-05-16 04:36
Just had a look back through the code. It's really weird this is only happening on Mongodb as the index is stored in memory and has no relation to the DB.

As it's stored in memory, can anyone confirm whether they are using this locally on a powerful machine or on a underpowered VM with small memory?

As I still cannot replicate myself. Can anyone confirm whether updating the Lunr version makes a difference? If not, can you confirm what browser and version you are using? Does the browser crash happen on multiple browsers?

**Comment by davidhr** [comment] 2017-05-17 09:03
I'm using a VM with 1G of memory. Only 7 articles for the moment. I tested with Safari and Chrome and both crashed. If I remember, with the latest version of Lunr I got an error message in console.

**Comment by mrvautin** [comment] 2017-05-18 00:27
What OS is your VM running and what version of Nodejs @davidhr? I will try replicate exactly.

**Comment by davidhr** [comment] 2017-05-18 14:27
The OS is Centos:
```
> cat /etc/redhat-release
CentOS release 6.9 (Final)
```

Nodejs:

````
> node -v
v6.6.0
`````

I'm using Mongodb 3.2.13

SeLinux is in Permissive mode:
```
> getenforce
Permissive
````
No firewall rules enabled.

**Comment by mrvautin** [comment] 2017-05-19 09:48
I've setup a Digital ocean droplet the same as you have mentioned and it's working fine. I even switched the index to also index the body of the article but still couldn't reproduce the error.

I'm not really sure where to go with this.

**Comment by davidhr** [comment] 2017-05-19 14:47
Ok I installed a fresh openKB in a dev folder with mongodb and did more tests. The freeze seems to happen only after inserting a new article.

**Comment by mrvautin** [comment] 2017-05-22 07:44
Looking at updating to Lunr 2.x and persisting the Index as it's now immutable in v 2.x. I will let you know when it's done.

**Comment by davidhr** [comment] 2017-05-22 07:57
Thanks!

**Comment by vikaskedia** [comment] 2017-05-25 00:27
The search has been freezing more frequently in our team across multiple different users on their own laptops.

When lunr is updated .. let me know so I can try it out and report back if that solves the problem.

@mrvautin appreciate your work.

**Comment by mrvautin** [comment] 2017-05-25 04:29
Looking for feedback on this fix. Hopefully nothing else was broken in the process. Could look to moving the index into the DB (NeDB/MongoDB) if it resolves the freezing issue and performance is not good with larger KB's.

**Comment by davidhr** [comment] 2017-05-29 07:59
@mrvautin the search function doesn't work anymore (tested with chrome & safari) and a click on the search button gives this error message: `lunr_index.search(...).forEach is not a function`.

**Comment by davidhr** [comment] 2017-05-29 08:08
yes: 
````
> cat data/searchIndex.json
{"version":"2.0.4","averageDocumentLength":null,"b":0.75,"k1":1.2,"fields":["kb_title","kb_keywords"],"documentVectors":[],"invertedIndex":[],"pipeline":["stemmer"]}
````

**Comment by mrvautin** [comment] 2017-05-29 08:15
The indexing isn't working properly. What DB option are you using? MongoDB or embedded?

**Comment by davidhr** [comment] 2017-05-29 08:17
Mongodb:
````
"database": {
            "type": "mongodb",
            "connection_string": "mongodb://127.0.0.1:27017/openkbdev2"
        }
````

**Comment by mrvautin** [comment] 2017-05-29 08:25
Thanks. Try again with commit: da745f8ad3cd2732534a3e8c7f954a6e68c58d83.

**Comment by davidhr** [comment] 2017-05-29 08:50
From a fresh install and only one article, I've now this in data/searchIndex.json:
````
{"version":"2.0.4","averageDocumentLength":3,"b":0.75,"k1":1.2,"fields":["kb_title","kb_keywords"],"documentVectors":[["592bdea3cafae14cce3865c5",[0,0.288,1,0.288,2,0.288]]],"invertedIndex":[["collabora",{"_index":0,"kb_title":{"592bdea3cafae14cce3865c5":{}},"kb_keywords":{}}],["nextcloud",{"_index":2,"kb_title":{"592bdea3cafae14cce3865c5":{}},"kb_keywords":{}}],["onlin",{"_index":1,"kb_title":{"592bdea3cafae14cce3865c5":{}},"kb_keywords":{}}]],"pipeline":["stemmer"]}
````

But same issue with the search function: no dropdown on keyup on the search field and when I click on the search button, I get this error message: `lunr_index.search(...).forEach is not a function` (error 500 on POST /search).

**Comment by mrvautin** [comment] 2017-05-29 08:56
I just cloned into a new folder, run install, added a new article and it's working fine.

Are you running with `NODE_ENV=production`? If so, run `npm run uglify` first.

**Comment by davidhr** [comment] 2017-05-29 09:13
@mrvautin are you using MongoDB for your tests? I did the uglify & NODE_ENV=production. Here is I get in the shell console on search: 
````
POST /search_api 200 9.575 ms - 665
TypeError: lunr_index.search(...).forEach is not a function
    at /var/www/html/dev/openkb/openKB/routes/index.js:1328:36
    at Layer.handle [as handle_request] (/var/www/html/dev/openkb/openKB/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/dev/openkb/openKB/node_modules/express/lib/router/route.js:137:13)
    at exports.restrict (/var/www/html/dev/openkb/openKB/routes/common.js:171:13)
    at Layer.handle [as handle_request] (/var/www/html/dev/openkb/openKB/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/dev/openkb/openKB/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/html/dev/openkb/openKB/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/html/dev/openkb/openKB/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/html/dev/openkb/openKB/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/html/dev/openkb/openKB/node_modules/express/lib/router/index.js:335:12)
POST /search 500 19.264 ms - -
````

**Comment by mrvautin** [comment] 2017-05-29 09:23
Whoops. See commit: 6e8756e2cecbd7ada46276c0b06c36605939e13f.

**Comment by davidhr** [comment] 2017-05-29 09:43
Ok thanks, no more error when I click on "search". The live works only if I use complete words from titles (or tags). For ex., if I've an article entitled "This is an article", I've to type "article" to get the dropdown; if I use "articl", no dropdown.

**Comment by mrvautin** [comment] 2017-05-29 09:49
I added wildcard/partial word matching. Try again with this commit: 4f78f8019f7468f8b2080eae43d89cb01680d7c9.

**Comment by davidhr** [comment] 2017-05-29 09:58
Thanks! it's working fine now. I just added two articles and the search isn't freezing at the moment! Maybe @vikaskedia and @william00179 could confirm this?

**Comment by mrvautin** [comment] 2017-05-30 08:18
Cool. Let me know how it goes reading the index off the disk performance wise. Hopefully it goes ok. Might need to move the index to the DB at some point if it gets slower with large indexes.

**Comment by mrvautin** [comment] 2017-05-30 08:19
Also need to work out a localstorage caching at some point too.

**Comment by vikaskedia** [comment] 2017-05-31 00:20
@mrvautin the new commits have introduced a bug in search.

Please see this video: 

https://youtu.be/k70pSynCIm8

**Comment by mrvautin** [comment] 2017-05-31 07:17
I can replicate the issue. Unfortunately it seems to be a Lunr issue. I'm looking into it further.

**Comment by vikaskedia** [comment] 2017-05-31 09:01
@mrvautin search is not freezing on my test URL.

I will replace the old version (where search freezes) with the new version organization wide once the search works.

**Comment by mrvautin** [comment] 2017-05-31 12:14
Having many issues with Lunr v2.x searching and indexing. Decided to roll back to 0.7.x. Fixed stemming of words and moved the search from the client/browser to the server. Let me know if it fixes both the freezing and the part word matches @vikaskedia @davidhr

**Comment by mrvautin** [comment] 2017-07-02 11:16
No action on this one so closing. If still occurring will reopen issue.

**Closed by mrvautin** 2017-07-02 11:16 UTC
